# data_gen/moves.toml
#
# Copyright (C) 2026 James Petersen <m@jamespetersen.ca>
# Licensed under MIT. See LICENSE

pound = 1
karate_chop = 2
double_slap = 3
comet_punch = 4
mega_punch = 5
pay_day = 6
fire_punch = 7
ice_punch = 8
thunder_punch = 9
scratch = 10
vice_grip = 11
guillotine = 12
razor_wind = 13
swords_dance = 14
cut = 15
gust = 16
wing_attack = 17
whirlwind = 18
fly = 19
bind = 20
slam = 21
vine_whip = 22
stomp = 23
double_kick = 24
mega_kick = 25
jump_kick = 26
rolling_kick = 27
sand_attack = 28
headbutt = 29
horn_attack = 30
fury_attack = 31
horn_drill = 32
tackle = 33
body_slam = 34
wrap = 35
take_down = 36
thrash = 37
double_edge = 38
tail_whip = 39
poison_sting = 40
twineedle = 41
pin_missile = 42
leer = 43
bite = 44
growl = 45
roar = 46
sing = 47
supersonic = 48
sonic_boom = 49
disable = 50
acid = 51
ember = 52
flamethrower = 53
mist = 54
water_gun = 55
hydro_pump = 56
surf = 57
ice_beam = 58
blizzard = 59
psybeam = 60
bubble_beam = 61
aurora_beam = 62
hyper_beam = 63
peck = 64
drill_peck = 65
submission = 66
low_kick = 67
counter = 68
seismic_toss = 69
strength = 70
absorb = 71
mega_drain = 72
leech_seed = 73
growth = 74
razor_leaf = 75
solar_beam = 76
poison_powder = 77
stun_spore = 78
sleep_powder = 79
petal_dance = 80
string_shot = 81
dragon_rage = 82
fire_spin = 83
thunder_shock = 84
thunderbolt = 85
thunder_wave = 86
thunder = 87
rock_throw = 88
earthquake = 89
fissure = 90
dig = 91
toxic = 92
confusion = 93
psychic = 94
hypnosis = 95
meditate = 96
agility = 97
quick_attack = 98
rage = 99
teleport = 100
night_shade = 101
mimic = 102
screech = 103
double_team = 104
recover = 105
harden = 106
minimize = 107
smoke_screen = 108
confuse_ray = 109
withdraw = 110
defense_curl = 111
barrier = 112
light_screen = 113
haze = 114
reflect = 115
focus_energy = 116
bide = 117
metronome = 118
mirror_move = 119
selfdestruct = 120
egg_bomb = 121
lick = 122
smog = 123
sludge = 124
bone_club = 125
fire_blast = 126
waterfall = 127
clamp = 128
swift = 129
skull_bash = 130
spike_cannon = 131
constrict = 132
amnesia = 133
kinesis = 134
softboiled = 135
hi_jump_kick = 136
glare = 137
dream_eater = 138
poison_gas = 139
barrage = 140
leech_life = 141
lovely_kiss = 142
sky_attack = 143
transform = 144
bubble = 145
dizzy_punch = 146
spore = 147
flash = 148
psywave = 149
splash = 150
acid_armor = 151
crabhammer = 152
explosion = 153
fury_swipes = 154
bonemerang = 155
rest = 156
rock_slide = 157
hyper_fang = 158
sharpen = 159
conversion = 160
tri_attack = 161
super_fang = 162
slash = 163
substitute = 164
struggle = 165
sketch = 166
triple_kick = 167
thief = 168
spider_web = 169
mind_reader = 170
nightmare = 171
flame_wheel = 172
snore = 173
curse = 174
flail = 175
conversion_2 = 176
aeroblast = 177
cotton_spore = 178
reversal = 179
spite = 180
powder_snow = 181
protect = 182
mach_punch = 183
scary_face = 184
faint_attack = 185
sweet_kiss = 186
belly_drum = 187
sludge_bomb = 188
mud_slap = 189
octazooka = 190
spikes = 191
zap_cannon = 192
foresight = 193
destiny_bond = 194
perish_song = 195
icy_wind = 196
detect = 197
bone_rush = 198
lock_on = 199
outrage = 200
sandstorm = 201
giga_drain = 202
endure = 203
charm = 204
rollout = 205
false_swipe = 206
swagger = 207
milk_drink = 208
spark = 209
fury_cutter = 210
steel_wing = 211
mean_look = 212
attract = 213
sleep_talk = 214
heal_bell = 215
return = 216
present = 217
frustration = 218
safeguard = 219
pain_split = 220
sacred_fire = 221
magnitude = 222
dynamic_punch = 223
megahorn = 224
dragon_breath = 225
baton_pass = 226
encore = 227
pursuit = 228
rapid_spin = 229
sweet_scent = 230
iron_tail = 231
metal_claw = 232
vital_throw = 233
morning_sun = 234
synthesis = 235
moonlight = 236
hidden_power = 237
cross_chop = 238
twister = 239
rain_dance = 240
sunny_day = 241
crunch = 242
mirror_coat = 243
psych_up = 244
extreme_speed = 245
ancient_power = 246
shadow_ball = 247
future_sight = 248
rock_smash = 249
whirlpool = 250
beat_up = 251
fake_out = 252
uproar = 253
stockpile = 254
spit_up = 255
swallow = 256
heat_wave = 257
hail = 258
torment = 259
flatter = 260
will_o_wisp = 261
memento = 262
facade = 263
focus_punch = 264
smelling_salt = 265
follow_me = 266
nature_power = 267
charge = 268
taunt = 269
helping_hand = 270
trick = 271
role_play = 272
wish = 273
assist = 274
ingrain = 275
superpower = 276
magic_coat = 277
recycle = 278
revenge = 279
brick_break = 280
yawn = 281
knock_off = 282
endeavor = 283
eruption = 284
skill_swap = 285
imprison = 286
refresh = 287
grudge = 288
snatch = 289
secret_power = 290
dive = 291
arm_thrust = 292
camouflage = 293
tail_glow = 294
luster_purge = 295
mist_ball = 296
feather_dance = 297
teeter_dance = 298
blaze_kick = 299
mud_sport = 300
ice_ball = 301
needle_arm = 302
slack_off = 303
hyper_voice = 304
poison_fang = 305
crush_claw = 306
blast_burn = 307
hydro_cannon = 308
meteor_mash = 309
astonish = 310
weather_ball = 311
aromatherapy = 312
fake_tears = 313
air_cutter = 314
overheat = 315
odor_sleuth = 316
rock_tomb = 317
silver_wind = 318
metal_sound = 319
grass_whistle = 320
tickle = 321
cosmic_power = 322
water_spout = 323
signal_beam = 324
shadow_punch = 325
extrasensory = 326
sky_uppercut = 327
sand_tomb = 328
sheer_cold = 329
muddy_water = 330
bullet_seed = 331
aerial_ace = 332
icicle_spear = 333
iron_defense = 334
block = 335
howl = 336
dragon_claw = 337
frenzy_plant = 338
bulk_up = 339
bounce = 340
mud_shot = 341
poison_tail = 342
covet = 343
volt_tackle = 344
magical_leaf = 345
water_sport = 346
calm_mind = 347
leaf_blade = 348
dragon_dance = 349
rock_blast = 350
shock_wave = 351
water_pulse = 352
doom_desire = 353
psycho_boost = 354
roost = 355
gravity = 356
miracle_eye = 357
wake_up_slap = 358
hammer_arm = 359
gyro_ball = 360
healing_wish = 361
brine = 362
natural_gift = 363
feint = 364
pluck = 365
tailwind = 366
acupressure = 367
metal_burst = 368
u_turn = 369
close_combat = 370
payback = 371
assurance = 372
embargo = 373
fling = 374
psycho_shift = 375
trump_card = 376
heal_block = 377
wring_out = 378
power_trick = 379
gastro_acid = 380
lucky_chant = 381
me_first = 382
copycat = 383
power_swap = 384
guard_swap = 385
punishment = 386
last_resort = 387
worry_seed = 388
sucker_punch = 389
toxic_spikes = 390
heart_swap = 391
aqua_ring = 392
magnet_rise = 393
flare_blitz = 394
force_palm = 395
aura_sphere = 396
rock_polish = 397
poison_jab = 398
dark_pulse = 399
night_slash = 400
aqua_tail = 401
seed_bomb = 402
air_slash = 403
x_scissor = 404
bug_buzz = 405
dragon_pulse = 406
dragon_rush = 407
power_gem = 408
drain_punch = 409
vacuum_wave = 410
focus_blast = 411
energy_ball = 412
brave_bird = 413
earth_power = 414
switcheroo = 415
giga_impact = 416
nasty_plot = 417
bullet_punch = 418
avalanche = 419
ice_shard = 420
shadow_claw = 421
thunder_fang = 422
ice_fang = 423
fire_fang = 424
shadow_sneak = 425
mud_bomb = 426
psycho_cut = 427
zen_headbutt = 428
mirror_shot = 429
flash_cannon = 430
rock_climb = 431
defog = 432
trick_room = 433
draco_meteor = 434
discharge = 435
lava_plume = 436
leaf_storm = 437
power_whip = 438
rock_wrecker = 439
cross_poison = 440
gunk_shot = 441
iron_head = 442
magnet_bomb = 443
stone_edge = 444
captivate = 445
stealth_rock = 446
grass_knot = 447
chatter = 448
judgment = 449
bug_bite = 450
charge_beam = 451
wood_hammer = 452
aqua_jet = 453
attack_order = 454
defend_order = 455
heal_order = 456
head_smash = 457
double_hit = 458
roar_of_time = 459
spacial_rend = 460
lunar_dance = 461
crush_grip = 462
magma_storm = 463
dark_void = 464
seed_flare = 465
ominous_wind = 466
shadow_force = 467
