name: Fuzz APWorld
on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]


jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
      - uses: Eijebong/ap-actions/setup-ap@main
        with:
          version: '0.6.3'
          python-version: '3.13'

      - uses: actions/checkout@master
        with:
          path: 'archipelago/worlds/pokemon_platinum'

      - name: Make apworld
        shell: bash
        run: |
          cd archipelago/
          uv venv
          uv pip install pyparsing
          cd worlds/pokemon_platinum
          make pokemon_platinum.apworld


      - name: Copy apworld
        shell: bash
        run: cp archipelago/worlds/pokemon_platinum/pokemon_platinum.apworld .

      - name: Clean up Archipelago clone
        shell: bash
        run: rm -rf archipelago

      - uses: Eijebong/ap-actions/fuzz@main
        with:
          apworld-path: pokemon_platinum.apworld
          ap-version: '0.6.3'
          python-version: '3.13'
          checkout: false
